#!/usr/bin/env bash


if [[ $# -ne 1 ]]; then
    echo "Usage: ./start tcp_serv_port_num"
    exit 1
fi

#make clean 2>&1 >/dev/null
make 

./tcp_server $1 & 
./tcp_client $1

ps | grep tcp_server | cut -d ' ' -f 2 | xargs kill
