#!/usr/bin/env bash


if [[ $# -ne 1 ]]; then
    echo "Usage: ./start tcp_serv_port_num " 
    exit 1
fi

let a=$1+1
let b=$a+1


make

./tcp_server $1 &
./tls_server $1 $a &
./tls_client $a $b &
./tcp_client $b

ps | grep *_server | awk '{print $1}' | xargs kill
