#!/usr/bin/env bash


if [[ $# -ne 2 ]]; then
    echo "Usage: ./start tcp_serv_port_num tls_serv_port_num" 
    exit 1
fi

#make clean 2>&1 >/dev/null
if ! [ -x ./tcp_server ]; then
	make 
fi

./tcp_server $1 &
./tls_server $1 $2 &
openssl s_client -cert client_cert/tls_client.crt -key client_cert/tls_client.key -connect 127.1:$2

ps | grep *_server | awk '{print $1}' | xargs kill
