#!/usr/bin/env bash


if [[ $# -ne 1 ]]; then
    echo "Usage: ./start tcp_serv_port_num " 
    exit 1
fi

let a=$1+1
let b=$a+1

./tcp_server $1 &
sleep 1s
./tls_server $1 $a &
sleep 1s
./tls_client $a $b &
sleep 1s
./tcp_client $b

ps | grep server | awk '{print $1}' | xargs kill
ps | grep client | awk '{print $1}' | xargs kill
